import { loadCldr, L10n } from "@syncfusion/ej2-base";
import * as gregorian from "cldr-data/main/fr-BE/ca-gregorian.json";
import * as currency from "cldr-data/main/fr-BE/currencies.json";
import * as numbers from "cldr-data/main/fr-BE/numbers.json";
import * as numberingSystems from "cldr-data/supplemental/numberingSystems.json";
import * as timeZoneNames from "cldr-data/main/fr-BE/timeZoneNames.json";
import { setCulture, setCurrencyCode } from "@syncfusion/ej2-base";
setCulture("fr-BE");
setCurrencyCode("DZD");
loadCldr(numberingSystems, gregorian, numbers,currency, timeZoneNames);

export default function Localization(props) {

  L10n.load({
    "fr-BE": {
      daterangepicker: {
        placeholder: "Choisir la période",
        startLabel: "Choisir la date de début",
        endLabel: "Choisir la date de fin",
        applyText: "Appliquer",
        cancelText: "Annuler",
        selectedDays: "Jours sélectionnés",
        days: "jours",
        customRange: "plage personnalisée",
      },
      uploader: {
        invalidMinFileSize: "La taille du fichier est trop petite! S'il vous plaît télécharger des fichiers avec une taille minimale de 10 Ko",
        invalidMaxFileSize: "La taille du fichier dépasse 28 Mo",
        invalidFileType: "Le type de fichier n'est pas autorisé",
        Browse: "Parcourir",
        Clear: "Clair",
        Upload: "Télécharger",
        dropFilesHint: "",
        uploadFailedMessage: "Impossible d'importer le fichier",
        uploadSuccessMessage: "Fichier téléchargé avec succès",
        removedSuccessMessage: "Fichier supprimé avec succès",
        removedFailedMessage: "Le fichier n'a pas pu être supprimé",
        inProgress: "Téléchargement",
        readyToUploadMessage: "Prêt à télécharger",
        remove: "Retirer",
        cancel: "Annuler",
        delete: "Supprimer le fichier",
      },
      schedule: {
        day: "journée",
        week: "La semaine",
        workWeek: "Semaine de travail",
        month: "Mois",
        agenda: "Ordre du jour",
        weekAgenda: "Agenda de la semaine",
        workWeekAgenda: "Agenda de la semaine de travail",
        monthAgenda: "Agenda du mois",
        today: "Aujourd'hui",
        noEvents: "Pas d'événements",
        emptyContainer: "Aucun événement n'est prévu ce jour-là.",
        allDay: "Toute la journée",
        start: "Début",
        end: "Fin",
        more: "plus",
        close: "Fermer",
        cancel: "Annuler",
        noTitle: "(Pas de titre)",
        delete: "Effacer",
        deleteEvent: "Supprimer un événement",
        deleteMultipleEvent: "Supprimer plusieurs événements",
        selectedItems: "Articles sélectionnés",
        deleteSeries: "Supprimer la série",
        edit: "modifier",
        editSeries: "Modifier la série",
        editEvent: "Modifier l'événement",
        createEvent: "Créer",
        subject: "Assujettir",
        addTitle: "",
        moreDetails: "Plus de détails",
        save: "sauvegarder",
        editContent: "Voulez-vous modifier uniquement cet événement ou une série entière?",
        deleteRecurrenceContent: "Voulez-vous supprimer uniquement cet événement ou une série entière?",
        deleteContent: "Êtes-vous sûr de vouloir supprimer cet événement?",
        deleteMultipleContent: "Êtes-vous sûr de vouloir supprimer les événements sélectionnés?",
        newEvent: "Nouvel évènement",
        title: "Titre",
        location: "Emplacement",
        description: "La description",
        timezone: "Fuseau horaire",
        startTimezone: "Début du fuseau horaire",
        endTimezone: "Fin du fuseau horaire",
        repeat: "Répéter",
        saveButton: "sauvegarder",
        cancelButton: "Annuler",
        deleteButton: "Effacer",
        recurrence: "Récurrence",
        wrongPattern: "Le modèle de récurrence n'est pas valide.",
        seriesChangeAlert: "Les modifications apportées à des instances spécifiques de cette série seront annulées et ces événements correspondront à nouveau à la série.",
        createError: "La durée de l'événement doit être plus courte que sa fréquence. Raccourcissez la durée ou modifiez le modèle de récurrence dans l'éditeur d'événement de récurrence.",
        recurrenceDateValidation: "Certains mois ont moins que la date sélectionnée. Pour ces mois, l'événement se produira à la dernière date du mois.",
        sameDayAlert: "Deux occurrences du même événement ne peuvent pas se produire le même jour.",
        editRecurrence: "Modifier la récurrence",
        repeats: "Répète",
        alert: "Alerte",
        startEndError: "La date de fin sélectionnée se produit avant la date de début.",
        invalidDateError: "La valeur de date saisie est invalide.",
        ok: "D'accord",
        occurrence: "Occurrence",
        series: "Séries",
        previous: "précédent",
        next: "Prochain",
        timelineDay: "Journée chronologique",
        timelineWeek: "Semaine chronologique",
        timelineWorkWeek: "Semaine de travail chronologique",
        timelineMonth: "Mois de la chronologie",
      },
      recurrenceeditor: {
        none: "Aucun",
        daily: "Par jour",
        weekly: "Par Semaine",
        monthly: "Par Mois",
        month: "Mois",
        yearly: "Annuel",
        never: "Jamais",
        until: "Jusqu'à",
        count: "Compter",
        first: "Premier",
        second: "Seconde",
        third: "Troisième",
        fourth: "Quatrième",
        last: "Dernier",
        repeat: "Répéter",
        repeatEvery: "Répéter tous les",
        on: "Répéter sur",
        end: "Fin",
        onDay: "journée",
        days: "Journées",
        weeks: "Semaines",
        months: "Mois",
        years: "Années",
        every: "chaque",
        summaryTimes: "fois",
        summaryOn: "sur",
        summaryUntil: "jusqu'à",
        summaryRepeat: "Répète",
        summaryDay: "journées",
        summaryWeek: "semaines",
        summaryMonth: "mois",
        summaryYear: "années",
        monthWeek: "Mois Semaine",
        monthPosition: "Position du mois",
        monthExpander: "Mois Expander",
        yearExpander: "Année Expander",
        repeatInterval: "Intervalle de répétition",
      },

      dialog: {
        close: "Fermer",
        open: "Ouvrir",
      },
      datetimepicker: {
        placeholder: "Date",
        today: "Aujourd'hui",
      },
      grid: {
        Add: "Ajouter",
        Edit: "Modifier",
        Cancel: "Annuler",
        CancelButton: "Annuler",
        Update: "Mettre à jour",
        Delete: "Supprimer",
        EmptyRecord: "Aucun enregistrement à afficher",
        EmptyDataSourceError: "Aucun enregistrement à afficher",
        Item: "Article",
        Print: "Imprimer",
        Columnchooser: "Colonne",
        ChooseColumns: "Choisir colonnes",
        Pdfexport: "Exporter PDF",
        Excelexport: "Exporter Excel",
        Search: "Recherche",
        Save: "Sauvgarder",
        SaveButton: "Sauvgarder",
        ConfirmDelete: "Voulez-vous vraiment supprimer cette ligne ?",
        CancelEdit: "Voulez-vous vraiment annuler les modifications ?",
        Matchs: "Aucun résultat",
        Export: "Exporter",
        EditOperationAlert: "Aucune ligne sélectionnée pour l'opération de modification",
        DeleteOperationAlert: "Aucune ligne sélectionnée pour l'opération de suppression",
      },
      pager: {
        FirstPage: "Première page",
        LastPage: "Dernière page",
        PreviousPage: "Page précédente",
        currentPageInfo: "{0} sur {1} pages",
        NextPage: "Page suivante",
        firstPageTooltip: "Première page",
        lastPageTooltip: "Dernière page",
        nextPageTooltip: "Page suivante",
        nextPagerTooltip: "Page suivante",
        previousPageTooltip: "page précédente",
        previousPagerTooltip: "page précédente",
        totalItemsInfo: `({0} ${props})`,
      },

      dropdowns: {
        actionFailureTemplate: "Modèle d'échec d'action",
        noRecordsTemplate: "Aucun enregistrement trouvé",
      },
    },
  });
}
